version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-udla
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Yoz0id3An0!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P $${MSSQL_SA_PASSWORD} -C -Q 'SELECT 1'"
      ]
      interval: 10s
      timeout: 5s
      retries: 10

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-init
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./init.sql:/init.sql
    entrypoint: >
      /opt/mssql-tools18/bin/sqlcmd 
      -S sqlserver 
      -U SA 
      -P Yoz0id3An0! 
      -C 
      -i /init.sql

  backend:
    container_name: user-api
    build:
      context: ./UserServiceAPI
      dockerfile: Dockerfile
    ports:
      - "5161:5161"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5161"



  frontend:
    build:
      context: ./frontperson
      dockerfile: Dockerfile
    container_name: next-frontend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:5161"
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mssql_data:
